/random/setSeeds 12 12

/LS/phys/enableoptical true
/LS/phys/yield 1.0

/run/initialize

# verbose config
/control/verbose 0
/run/verbose 0
/tracking/verbose 0

/LS/ana/output toy
/My/ana/output rb1.root
/My/ana/activate true
/My/ana/birks1 6.5e-3 g/cm2/MeV

/LS/gun/parNum 1
/LS/gun/particle1 gamma
/LS/gun/energy1 0.5 MeV
/LS/gun/momtype1 iso
/LS/gun/position1 0 0 0
/LS/gun/particle2 e-
/LS/gun/energy2 1.0
/LS/gun/momtype2 iso
/LS/gun/position2 0 0 0

/LS/sd/efficiency 0.18

/run/beamOn 10
